accounts/urls.py
app_name = 'accounts'


from django.urls import path,include
from .views import RegisterView,guest_register_view,LoginView


urlpatterns = [
 path('register/',RegisterView.as_view(),name='register'),
 path('register/guest/',guest_register_view,name='guest_register'),
 path('login/',LoginView.as_view(),name='login'),
]

carts/urls.py
app_name = 'cart'
from django.urls import path, include
from .views import cart_home, cart_update, checkout_home, checkout_done_view

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import HomePageView, BootstrapView
from django.contrib.auth.views import LogoutView
from accounts.views import guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
from .views import contact_page

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('guest/register', guest_register_view, name='guest_register'),
    path('contact/', contact_page, name='contact'),
    path('products/', include('products.urls', namespace='products')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('bootstrap/', BootstrapView.as_view(), name='bootstrap'),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path,include
from .views import ProductListView,ProdcutDetailSlugView


app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProdcutDetailSlugView.as_view(), name='details'),
]

templates/base/nav.html
{# variables handling navbar active #} {% url 'home' as home_url %} {% url 'products:list' as products_list %} {% url 'logout' as logout_url %} {% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
	<div class="container">


		<a class="navbar-brand" href="{% url 'home' %}"> {% if brand_name %}{{brand_name}}{% else %}eCommerce platform {% endif %}</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
													    aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link {% if request.path == home_url %} active {% endif %}" href="{% url 'home' %}">Home
						<span class="sr-only">(current)</span>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if request.path == home_url %} active {% endif %}" href="{% url 'home' %}">Contact</a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if request.path == products_list %} active {% endif %}" href="{% url 'products:list' %}">Products</a>
				</li>
				{% if request.user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link {% if request.path == logout_url  %} active {% endif %}" href="{% url 'logout' %}">Logout</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link {% if request.path == products_list %} active {% endif %}" href="{% url 'accounts:login' %}">Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if request.path == products_list %} active {% endif %}" href="{% url 'accounts:register' %}">Register</a>
				</li>

				{% endif %}
				<li class="nav-item">
					<a class="nav-link {% if request.path == cart_url %} active {% endif %}" href="{% url 'cart:home' %}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span><i class="fa fa-shopping-cart"></i></a>
				</li>

			</ul>

			{% include 'search/snippets/search-form.html' %}




		</div>
	</div>
</nav>